### ISSUE TITLE
Docker Compose Up doesn't work in Puppet manifest

### ISSUE THREAD

**Issue by Balfear** [bibbox/kit-eb3kit#1]

**Comment by reihsr** [comment]
==> default: Error: /Stage[main]/Vmbuilder/Docker_compose[/opt/bibbox/sys-activities/docker-compose.yml]: Could not evaluate: Execution of '/usr/bin/docker ps --format {{.Label "com.docker.compose.service"}} --filter label=com.docker.compose.project=sysactivities' returned 1: template: :1:2: executing "" at <.Label>: Label is not a method but has arguments

**Comment by Balfear** [comment]
Fixed.
