### ISSUE TITLE
Linux Parameters

### ISSUE THREAD

**Issue by lomadi** [bibbox/kit-eb3kit#5]
some paramters for UBUNTU has to be optimized

- number of open files (do we have a leak somewhere ?)
- configs for the ELK stack

**Comment by Balfear** [comment]
I think the problem you are referring to had to do with a double reload of the apache service, which crashed the apache and rendered the BIBBOX unusable until it is restarted.
We already implemented a fix for that and hopefully it also fixes the issues you have experienced.
I'm closing the issue for now, but feel free to reopen it with additional information if the problem reoccurs.
