### ISSUE TITLE
vmadmin user

### ISSUE THREAD

**Issue by lomadi** [bibbox/kit-eb3kit#7]
there is NO user directory, 
user has no login environment

in the docu
explain what the user is for, what is his password
login to machine with vagrant ssh or with SSH and the user and the port given in ....
do we need two ssh ports?

**Comment by Balfear** [comment]
The home directory for vmadmin is already implemented and working. See BIBBOX "demo-new" in "/home/vmadmin".
I will add an description for the user to the docs.
Closing this issue for now.
